project_root: /home/mohsen/work/yorku/apply/pulsenics/
paths:
  dataset: bcp/data/interview-dataset.csv # This is the path to the battery capacity dataset

  figures: bcp/figures/ # This is the directory where figures will be saved
  

training:
  model_name: bcp_train # Name of the model to be trained
  version: v1 # Version of the model, can be used to differentiate between different training runs

  output_base: bcp/weights # Base directory where the model weights will be saved
  checkpoint_dir: ${training.output_base}/${training.model_name}_${training.version}/checkpoints # Directory where model checkpoints will be saved this is the place holder and `construct_training_paths` will replace it with the actual path
  final_model_dir: ${training.output_base}/${training.model_name}_${training.version}/final_model # Directory where the final model will be saved this is the place holder and `construct_training_paths` will replace it with the actual path

  val_size: 0.1 # Proportion of the data to use for the validation set
  test_size: 0.2 # Proportion of the data to use for the test set
  random_state: 42 # Random seed for reproducibility
  latent_dim: 4 # Dimensionality of the latent space in the VQ-VAE model
  num_embeddings: 5 # Number of embeddings in the VQ-VAE model
  commitment_cost: 0.25 # Commitment cost for the VQ-VAE model
  hidden_dims: [128, 256, 512] # Hidden dimensions for the VQ-VAE model
  num_epochs: 100 # Number of epochs to train the model
  batch_size: 32 # Batch size for training
  learning_rate: 0.001 # Learning rate for the optimizer